services:
  - type: web
    name: webMVC_Project
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx256m -server"
      - key: DB_URL
        value: "jdbc:postgresql://My_Notes:5432/production_db"
      - key: LOG_LEVEL
        value: "INFO"