services:
  - type: web
    name: my-notes-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: JAVA_OPTS
        value: "-Xms128m -Xmx400m"
      - key: CATALINA_OPTS  
        value: "-server -Xms128m -Xmx400m"