# Exported from Render on 2025-06-30T04:33:54Z
services:
- type: web
  name: webMVC_Project
  runtime: docker
  repo: https://github.com/MyShip/webMVC_Project
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: LOG_LEVEL
    sync: false
  - key: DB_URL
    sync: false
  - key: JAVA_OPTS
    sync: false
  region: ohio
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
version: "1"